import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service - SetReady',
  description: 'SetReady terms of service for Canadian film industry training. Learn about account usage, payments, and user conduct.',
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto p-8 bg-white shadow-lg rounded-xl my-8">
      <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
      <p className="text-gray-600 mb-8">Last Updated: April 11, 2026</p>

      <div className="bg-yellow-50 p-4 rounded-lg mb-8 border-l-4 border-yellow-500">
        <p className="text-sm text-yellow-800">
          <strong>By using SetReady, you agree to these terms.</strong> If you do not agree, please do not use our Service.
        </p>
      </div>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
        <p>By downloading, accessing, or using SetReady ("the App", "we", "our", "us"), you agree to be bound by these Terms of Service. These terms apply to all users of the App.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">2. Description of Service</h2>
        <p>SetReady provides educational training for Canadian film industry background performers, including:</p>
        <ul className="list-disc pl-6 mt-2 space-y-1 text-gray-700">
          <li>Training modules and lessons on film set terminology</li>
          <li>Quizzes and assessments to test knowledge</li>
          <li>Progress tracking and streak monitoring</li>
          <li>Completion certificate generation</li>
          <li>Union rate calculators</li>
          <li>Voucher tracking tools</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">3. Account Registration</h2>
        <h3 className="font-semibold mt-2">3.1 Eligibility</h3>
        <p>You must be at least 13 years old to create an account. By creating an account, you confirm that you are 13 years of age or older. If we discover that an account was created by someone under 13, we will terminate the account and delete all associated data.</p>
        
        <h3 className="font-semibold mt-3">3.2 Account Responsibility</h3>
        <p>You are responsible for:</p>
        <ul className="list-disc pl-6 mt-1 space-y-1 text-gray-700">
          <li>Providing accurate and complete information</li>
          <li>Keeping your login credentials secure</li>
          <li>All activity that occurs under your account</li>
          <li>Not sharing your account with others</li>
        </ul>
        
        <h3 className="font-semibold mt-3">3.3 Account Termination</h3>
        <p>You may delete your account at any time through the Settings page. We may suspend or terminate accounts that violate these terms without notice.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">4. User Conduct</h2>
        <p>You agree NOT to:</p>
        <ul className="list-disc pl-6 mt-2 space-y-1 text-gray-700">
          <li>Share quiz answers or certificates fraudulently</li>
          <li>Attempt to bypass security measures or access unauthorized areas</li>
          <li>Use the App for any illegal purpose</li>
          <li>Harass, abuse, or impersonate other users</li>
          <li>Reverse engineer, copy, or modify the App's code</li>
          <li>Post inappropriate, offensive, or defamatory content</li>
          <li>Use automated scripts to interact with the App</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">5. Intellectual Property</h2>
        <h3 className="font-semibold mt-2">5.1 Our Content</h3>
        <p>All lesson content, quiz questions, course materials, logos, and designs are owned by SetReady and protected by Canadian and international copyright laws.</p>
        
        <h3 className="font-semibold mt-3">5.2 Your Content</h3>
        <p>You retain ownership of your quiz answers and progress data. By using the App, you grant SetReady a license to use this data to provide the Service and improve our content.</p>
        
        <h3 className="font-semibold mt-3">5.3 Certificates</h3>
        <p>Certificates generated by the App are proof of completion for the specific course. Certificates do not guarantee employment, union membership, or specific career outcomes.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">6. Payments and Refunds</h2>
        <h3 className="font-semibold mt-2">6.1 Pricing</h3>
        <p>Current pricing is displayed in the App. We reserve the right to change prices with reasonable notice. Any price changes will not affect existing paid subscriptions during their current term.</p>
        
        <h3 className="font-semibold mt-3">6.2 Refund Policy</h3>
        <p>Due to the digital nature of our educational content:</p>
        <ul className="list-disc pl-6 mt-1 space-y-1 text-gray-700">
          <li>Refunds are available within 30 days of purchase</li>
          <li>To request a refund, contact support@setready.com</li>
          <li>Refunds are processed within 5-10 business days</li>
        </ul>
        
        <h3 className="font-semibold mt-3">6.3 Free Trial</h3>
        <p>If a free trial is offered, you must cancel before the trial ends to avoid charges. Failure to cancel will result in automatic billing at the then-current rate.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">7. Third-Party Services</h2>
        <p>The App integrates with the following third-party services, which have their own terms and privacy policies:</p>
        <ul className="list-disc pl-6 mt-2 space-y-1 text-gray-700">
          <li><strong>Supabase:</strong> Database and authentication</li>
          <li><strong>Vercel:</strong> App hosting and analytics</li>
        </ul>
        <p className="mt-2">We are not responsible for the practices of these third parties.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">8. Disclaimer of Warranties</h2>
        <p>The App is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not warrant that:</p>
        <ul className="list-disc pl-6 mt-2 space-y-1 text-gray-700">
          <li>The App will be uninterrupted, timely, secure, or error-free</li>
          <li>Quiz results will lead to employment or career advancement</li>
          <li>All information is completely accurate or current</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">9. Limitation of Liability</h2>
        <p>To the maximum extent permitted by law, SetReady and its owners, employees, and affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the App, including but not limited to:</p>
        <ul className="list-disc pl-6 mt-2 space-y-1 text-gray-700">
          <li>Loss of profits, data, or goodwill</li>
          <li>Personal injury or property damage</li>
          <li>Unauthorized access to your account</li>
        </ul>
        <p className="mt-2">Our total liability shall not exceed the amount you paid us, if any, in the past 12 months.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">10. Indemnification</h2>
        <p>You agree to indemnify and hold SetReady harmless from any claims, damages, losses, and expenses arising from:</p>
        <ul className="list-disc pl-6 mt-2 space-y-1 text-gray-700">
          <li>Your violation of these Terms</li>
          <li>Your use of the App</li>
          <li>Your violation of any third-party rights</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">11. Governing Law</h2>
        <p>These Terms shall be governed by and construed in accordance with the laws of British Columbia, Canada, without regard to its conflict of law provisions.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">12. Dispute Resolution</h2>
        <p>Any disputes arising from these Terms or your use of the App shall be resolved through binding arbitration in Vancouver, British Columbia, Canada. You waive the right to participate in class actions.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">13. Changes to Terms</h2>
        <p>We may update these Terms from time to time. We will notify you of material changes by:</p>
        <ul className="list-disc pl-6 mt-2 space-y-1 text-gray-700">
          <li>Posting the new Terms on this page</li>
          <li>Updating the "Last Updated" date</li>
          <li>Sending an email notification for significant changes</li>
        </ul>
        <p className="mt-2">Continued use of the App after changes constitutes acceptance of the new Terms.</p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">14. Contact Us</h2>
        <p className="mb-2"><strong>For legal matters:</strong> <a href="mailto:legal@setready.com" className="text-blue-600 hover:underline">legal@setready.com</a></p>
        <p><strong>For general support:</strong> <a href="mailto:support@setready.com" className="text-blue-600 hover:underline">support@setready.com</a></p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">15. Entire Agreement</h2>
        <p>These Terms constitute the entire agreement between you and SetReady regarding your use of the App, superseding any prior agreements.</p>
      </section>

      <div className="mt-8 pt-4 border-t border-gray-200 text-center text-sm text-gray-500">
        <Link href="/privacy" className="text-blue-600 hover:underline">Privacy Policy</Link>
        {' • '}
        <Link href="/dashboard" className="text-blue-600 hover:underline">Back to Dashboard</Link>
      </div>
    </div>
  );
}